### ISSUE TITLE
Cannot start start.js??

### ISSUE THREAD

**Issue by mitchellurgero** [byteball/obyte-hub#3]
I get the following error and cannot seem to get past it....

```
> byteball-hub@0.1.5 start /home/mitchell/Documents/byteball/byteball-hub
> node start.js

finished hub conf
merged app root conf from /home/mitchell/Documents/byteball/byteball-hub/conf.js
app dir /home/mitchell/Documents/byteball/byteball-hub
not using user conf: Error: Cannot find module '/home/mitchell/.config/byteball-hub/conf.json'
app dir /home/mitchell/Documents/byteball/byteball-hub
path=/home/mitchell/.config/byteball-hub/
createDatabaseIfNecessary byteball.sqlite
takeConnectionFromPool will wait for ready
Sat Apr 15 2017 02:16:09 GMT-0500 (CDT): takeConnectionFromPool will wait for ready
module.js:327
    throw err;
    ^

Error: Cannot find module 'byteballcore/network'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/mitchell/Documents/byteball/byteball-hub/start.js:5:15)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
```

Running Debian Sid. Any help would be great!

**Comment by tonyofbyteball** [comment]
did you do `npm install`?

**Comment by mitchellurgero** [comment]
Yes. I followed instructions in readme

**Comment by tonyofbyteball** [comment]
what's your node version?

**Comment by mitchellurgero** [comment]
Version 4.7.2

**Comment by mitchellurgero** [comment]
Sorry to bump - but would really like to get this done. Please let me know! thanks!

**Comment by tonyofbyteball** [comment]
If you upgrade to 6.x, it'll work as is.
Otherwise you can edit the paths in `require()` to make them one level deeper, e.g.
```
var network = require('byteballcore/network');
```
becomes
```
var network = require('byteball-relay/node_modules/byteballcore/network');
```

**Comment by mitchellurgero** [comment]
Thank you. I will work on this!

**Comment by mitchellurgero** [comment]
hmmm finally got it to load without error but it is not listening on the configured port...?

**Comment by mitchellurgero** [comment]
bump

**Comment by tonyofbyteball** [comment]
It should be enabled by default https://github.com/byteball/byteball-hub/blob/master/conf.js#L11

How do you know it is not listening?

**Comment by mitchellurgero** [comment]
netstat reveals no open port 6611. also cannot connect to that port with any wallet "Connection Refused" Firewall is NOT enabled for testing with same error.

**Comment by tonyofbyteball** [comment]
Assuming you didn't edit/override the setting, see in the first lines of its log, it should print that it is listening on port 6611.

**Comment by mitchellurgero** [comment]
It does not print that it is listening on a port, nor does it print anything regarding errors:

```
:~/byteball-hub$ cat log.txt
finished hub conf
merged app root conf from /home/user/byteball-hub/conf.js
app dir /home/user/byteball-hub
not using user conf: Error: Cannot find module '/home/user/.config/byteball-hub/conf.json'
app dir /home/user/byteball-hub
path=/home/user/.config/byteball-hub/
createDatabaseIfNecessary byteball-light.sqlite
takeConnectionFromPool will wait for ready
Tue Apr 25 2017 07:59:55 GMT-0500 (CDT): takeConnectionFromPool will wait for ready
Tue Apr 25 2017 07:59:55 GMT-0500 (CDT): starting network
Tue Apr 25 2017 07:59:55 GMT-0500 (CDT): stat null
Tue Apr 25 2017 07:59:55 GMT-0500 (CDT): db is now ready
Tue Apr 25 2017 07:59:55 GMT-0500 (CDT): opening new db connection
Tue Apr 25 2017 07:59:55 GMT-0500 (CDT): db is now ready
Tue Apr 25 2017 07:59:55 GMT-0500 (CDT): opened db
Tue Apr 25 2017 07:59:55 GMT-0500 (CDT): db version 6
Tue Apr 25 2017 07:59:55 GMT-0500 (CDT): starting
Tue Apr 25 2017 07:59:55 GMT-0500 (CDT): outbound peers:
Tue Apr 25 2017 07:59:55 GMT-0500 (CDT): will connect to wss://byteball.org/bb
Tue Apr 25 2017 07:59:55 GMT-0500 (CDT): connectToPeer done
Tue Apr 25 2017 07:59:55 GMT-0500 (CDT): long query took 30ms:
INSERT OR IGNORE INTO peer_hosts (peer_host) VALUES (?), byteball.org
load avg: 0.2421875, 0.2958984375, 0.31982421875
Tue Apr 25 2017 07:59:55 GMT-0500 (CDT): will insert peer wss://byteball.org/bb

```

**Comment by tonyofbyteball** [comment]
> createDatabaseIfNecessary byteball-light.sqlite

Hub cannot be light.  Switch to full please.  Light clients never listen.

**Comment by mitchellurgero** [comment]
oh. lol wow I am a dunce sometimes. Thanks! Will give that a shot!

**Comment by mitchellurgero** [comment]
Would you be able to provide an example apache configuration?

**Comment by mitchellurgero** [comment]
OK one more issue with the hub and then I am out of your hair, when connected, it seems to be working and such, however:
1. I CAN send messages to and from a device on the same hub and a different hub [GOOD]
2. I CANNOT receive bytes on my hub [BAD]

when opening a wallet connected to my hub it gives a "No byteball prefix" error. 

Any pointers on where to look?

**Comment by mitchellurgero** [comment]
you know what - it needs to download the dag first doesn't it lol ooooopppssss

**Comment by mitchellurgero** [comment]
12 hours and still when opening a wallet connected to my hub it gives a "No byteball prefix" error. Is this a common issue or am I doing something wrong?

**Comment by mitchellurgero** [comment]
bump

**Comment by tonyofbyteball** [comment]
You just open the wallet? or you click a link?
What if you change the hub back to the default?

**Comment by mitchellurgero** [comment]
Changing to the default hub seems to solve the error message, but I want to use my own hub. Would also like to note that I can send and receive messages using my hub but it's been over 24 hours and I still cannot send and receive bytes. Looking at the server logs reveal that it is syncing and looking at the db also confirms this. however it is very slow.

**Comment by tonyofbyteball** [comment]
what's your hub address? let me try it myself

**Comment by mitchellurgero** [comment]
For my device? Or actual hub?

Well here is my hub: byteball.urgero.org/bb

**Comment by mitchellurgero** [comment]
Also thank you for all the help - you have been great so far!

**Comment by tonyofbyteball** [comment]
I changed my settings to your hub and I can chat with the transition bot, so it works.  No error messages.

**Comment by mitchellurgero** [comment]
I know chatting works, but I am not able to receive bytes. Also did you get the no byteball prefix error?

**Comment by tonyofbyteball** [comment]
No errors.
That you are not able to receive bytes, is hardly related to the hub.  Your wallet might not be synced yet.

**Comment by mitchellurgero** [comment]
I am going to reset my wallet and see if that resolves my issues. Also my wallet (Not hub) is in light mode. Would that make a difference?

**Comment by mitchellurgero** [comment]
Either way - Thank you for all the help! I am really new to how byteball works and realizing it is nothing like running a bitcoin node lol

**Comment by mitchellurgero** [comment]
Complete reset on the wallet seems to have worked for me. Must have just been a sync error, even in light mode - but never the less, working! Thank you good sir! You may close this issue now!
